config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  resources :registrations

  get "session/new" => "sessions#new", as: :sign_in
  post "session" => "sessions#create", as: :authenticate_session
  get "session/destroy" => "sessions#destroy", as: :sign_out

  post "/follows" => "follows#create", as: :start_following
  post "/follows/stop" => "follows#destroy", as: :stop_following

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  paginates_per 8

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user, :body, presence: true
  paginates_per 4

  def self.timeline(user)
    follower_ids = user.following_users.map(&:id)
    all_ids= follower_ids << user.id
    Post.where(user_id: all_ids).order("created_at DESC")
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password validations: false
  has_many :posts

  acts_as_followable
  acts_as_follower

  validates :name, presence: true, uniqueness: true, :if => :active_or_login?
  validates :password, confirmation: true, :if => :active_or_login?
  validates :facebook, presence: true, :if => :active_or_personal?
  validates :email, presence: true, uniqueness: true, :if => :active_or_personal?

  def active?
    status == 'active'
  end

  def active_or_login?
    status.include?('login') || active?
  end

  def active_or_personal?
    status.include?('personal') || active?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    if signed_in?
      @current_user = User.find_by id: session[:user_id]
    else
      redirect_to sign_in_path
    end
  end

  def signed_in?
    session[:user_id].to_i > 0
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  before_action :authenticate_user!

  def create
    their_user_id = params[:user_id]
    me = @current_user
    them = User.find(their_user_id)

    me.follow(them)

    redirect_to root_path
  end

  def destroy
    their_user_id = params[:user_id]
    me = @current_user
    them = User.find(their_user_id)

    me.stop_following(them)

    redirect_to root_path

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def index
    @posts = Post.all.order("created_at DESC").page params[:page]
    @users = User.all
    @timeline = Post.timeline(@current_user).page params[:page]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params.require(:post).permit(:body)
    @post.user = @current_user
    if @post.save
      redirect_to root_path, notice: "so whatcha watcha watcha want..."
    else
      render :new
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  include Wicked::Wizard

  steps :login, :personal

  def show

    if session[:new_user_id].blank?
      @user = User.create!
      session[:new_user_id] = @user.id
    end
    @user = User.find_by id:session[:new_user_id]

    render_wizard
  end


  def update
  @user = User.find session[:new_user_id]

  @user.update_attribute(:status, step.to_s)
  if step == steps.last
    @user.update_attribute(:status, 'active')
  end

  case step
    when :login
      @user.update(params.require(:user).permit(:name, :password, :password_confirmation))
    when :personal
      @user.update(params.require(:user).permit(:email, :facebook))

      session[:user_id] = @user.id
    end
    render_wizard @user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    name = params[:name]
    password = params[:password]

    user = User.find_by name: name
    if user.try(:authenticate, password)
       session[:user_id] = user.id
       redirect_to root_path
    else
      redirect_to sign_in_path, alert: "Name or Password not found"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:new_user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.0/css/font-awesome.min.css">
<link rel="stylesheet" href="path/to/your/css/slide-social-buttons.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>
</head>
<body>

<%= yield %>
<%= javascript_include_tag :application %>
</body>
</html>

app/views/posts/index.html.erb
<html>
<div class="container">
  <h1 class="jumbotron">its the TWITTS</h1>

  <% if @current_user %>
  <%= link_to "Sign Out", sign_out_path, class: "btn btn-primary pull-right" %>
  <% end %>
  <% unless @current_user %>
  <%= link_to "Sign In", sign_in_path, class: "btn btn-primary pull-right" %>
  <%= link_to "Sign Up", registrations_path(:login), class: "btn btn-primary pull-right" %>
<% end %>

  <%= link_to "Add New Post", new_post_path, class: "btn btn-primary" %>

  <br>
  <br>

  <div class="container">
  <div class="follow">


  <div class="col-md-3 col-xs-2">
  <h4>Following</h4>
  <% @current_user.all_following.each do |user| %>
    <li style="list-style-type: none;"><%= link_to "unfollow", stop_following_path(user_id: user.id), method: :post, class: "btn btn-danger btn-xs", data: {confirm: "Really stop following the super awesome tweets from #{user.name}?"} %>
      - <%= user.name %> </li>
  <% end %>

  <h4> Follow These guys too </h4>
  <% @users.each do |user| %>
      <% unless @current_user.following?(user) %>
      <li style="list-style-type: none;"><%= link_to "follow", start_following_path(user_id: user.id), method: :post, class: "btn btn-success btn-xs"%>
       - <%= user.name %> </li>
      <% end %>
  <% end %>
</div>

    <div class="col-md-9 col-xs-9">
      <h4>What people you follow are saying:</h4>
      <br>
    <% @timeline.each do |w| %>
    <ul>
      <h5><%= w.body %></h5>
      - <%= w.user.name %>
    </ul>
    <% end %>
    <%= paginate @timeline %>
    </div>
  </div>



  <ul style="list-style: none;" class="col-md-9">
    <h4>Read what others are saying:</h4>
    <% @posts.each do |post| %>
    <ul>
      <%= post.body %> <br>
      - <%= post.user.name %>
    </ul>
    <br>
    <% end %>
    <%= paginate @posts %>

  </ul>
  <br>
  <!-- Facebook -->
  <div class="slide-social">
      <div class="button">
          <!-- Place FB Like Button Here -->
      </div>
      <div class="facebook icon">
          <i class="icon-facebook"></i>
      </div>
      <div class="facebook slide"><p>like</p></div>
  </div>
  <!-- Twitter -->
  <div class="slide-social">
    <div class="button">
        <!-- FYI: Add your Twitter username to data-via -->
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.twitter.com/justinmckelvey" data-text="Slide Buttons" data-via="JWade">tweet</a>
    </div>
    <div class="twitter icon">
        <i class="icon-twitter"></i>
    </div>
    <div class="twitter slide"><p>tweet</p></div>
  </div>
  <!-- Linkedin -->
  <div class="slide-social">
      <div class="button">
          <script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
          <script type="IN/Share" data-url="" data-counter="center"></script>
      </div>
      <div class="linkedin icon">
          <i class="icon-linkedin"></i>
      </div>
      <div class="linkedin slide"><p>share</p></div>
  </div>
</div>




<footer class="col-md-offset-1">Copywright JWADE - 2015</footer>
</html>

app/views/posts/new.html.erb
<h2> Sooo you wanna contribute eh? </h2>

<div class="container">
<%= simple_form_for @post do |f| %>
  <%= f.input :body, hint: " Write an awesome post here", label: "text" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>